gitpub/cms/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^login', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    url(r'', views.index, name='index')
]

gitpub/courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new/', views.create_course_form_get, name='create_course_form_get'),
    url(r'^post_new/', views.create_course_form_post, name='create_course_form_post'),
]

gitpub/gitpub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include(('courses.urls', 'courses'), namespace='courses')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'', include(('cms.urls', 'cms'), namespace='cms')),
]

gitpub/cms/models.py
"""
Models module
"""
import datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    Abstract class for RegisteredUser
    """
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

class AnonymousUser(CustomUser):
    """
    AnonymousUser
    """
    def save(self, *args, **kwargs):
        self.pk = 0
        self.name = "Anonymous User"
        try:
            super(AnonymousUser, self).save(*args, **kwargs)
        except:
            AnonymousUser.objects.get(id=0)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=0, name="Anonymous User")
        return obj


class RegisteredUser(CustomUser):
    """
    Abstract class for Admin and Student
    """
    registry = models.IntegerField()
    username = models.CharField(max_length=150, unique=True)
    email = models.CharField(max_length=150, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'name', 'registry']

class Material(models.Model):
    """
    Materials belong to projects
    """
    url = models.CharField(max_length=140)


class Period(models.Model):
    """
    A class belongs to a period (Semester 1 or 2)
    """
    FIRST = 1
    SECOND = 2
    SEMESTER_CHOICES = (
        (FIRST, 'First'),
        (SECOND, 'Second')
    )
    YEAR_CHOICES = [(r, r) for r in range(2000, datetime.date.today().year+1)]
    year = models.IntegerField(choices=YEAR_CHOICES)
    semester = models.IntegerField(choices=SEMESTER_CHOICES)

    def __str__(self):
        return ", ".join([self.semester, self.year])


class Course(models.Model):
    """
    A course is created by an user and belongs to a class
    """
    description = models.CharField(max_length=140)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Classroom(models.Model):
    """
    A classroom can be created and/or enrolled by an user
    and belongs to a course
    """
    name = models.CharField(max_length=50)
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name='classrooms'
    )
    owner = models.ForeignKey(
        RegisteredUser, 
        on_delete=models.CASCADE,
        related_name='owned_classrooms'
    )
    enrolled_users = models.ManyToManyField(
        RegisteredUser,
        related_name='enrolled_classrooms'
    )
    period = models.ForeignKey(
        Period,
        on_delete=models.CASCADE,
        related_name='classrooms'
    )

    def __str___(self):
        return self.name

    class Meta:
        ordering = ('course', 'period', 'name')


class Project(models.Model):
    """
    A project belongs to a classroom, has comments and material
    """
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=140)
    views = models.IntegerField(default=0)
    classroom = models.ManyToManyField(
        Classroom,
        related_name='projects'
    )

    def __str__(self):
        return self.name


class Comment(models.Model):
    """
    A comment is written by an user to a project.
    """
    text = models.CharField(max_length=140)
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='comments'    
    )

    def __str__(self):
        return self.text

gitpub/courses/models.py
from django.db import models

# Create your models here.

gitpub/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from gitpub.logging import debug

# Create your views here.
@debug
def index(request):
    return render(request, 'index.html')

@debug
def login(request):
    return render(request, 'login.html')

@debug
def register(request):
    return render(request, 'register.html')

gitpub/courses/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from gitpub.logging import debug, GitPubDebugger
from cms.models import Course

# Create your views here.
@debug
def create_course_form_get(request):
    # return HttpResponse('This is create course')
    return render(request, 'create_course_form.html')

@debug
def create_course_form_post(request):
    try:
        Course.objects.create(
            description="Test",
            name="Name"
        )
    except:
        debugger_instance = GitPubDebugger()
        debugger_instance.error("Failed to create course")
    return HttpResponseRedirect(reverse('cms:index'))

gitpub/cms/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

gitpub/cms/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="GitPub Team">
  <title>GitPub</title>
  <!-- Favicon -->
  <link href="../static/assets/img/brand/gitpub.png" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="../static/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
  <link href="../static/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="../static/assets/css/argon.css?v=1.0.1" rel="stylesheet">
  <!-- Docs CSS -->
  <link type="text/css" href="../static/assets/css/docs.min.css" rel="stylesheet">
</head>

<body>

  <main>
    <section class="section section-shaped pt-0">
      <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div class="container pt-lg-md">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="row justify-content-center session-brand">
              <img class="session-brand" src="../static/assets/img/brand/gitpub.png">
            </div>
            <div class="row justify-content-center session-brand">
              <h2 class="text-light">Sign in to GitPub</h2>
            </div>
            <div class="card bg-secondary shadow border-0">
              <div class="card-header bg-white pb-5">
                <div class="text-muted text-center mb-3">
                  <small>Sign in with</small>
                </div>
                <div class="btn-wrapper text-center">
                  <a href="#" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon">
                      <img src="../static/assets/img/icons/common/github.svg">
                    </span>
                    <span class="btn-inner--text">Github</span>
                  </a>
                  <a href="#" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon">
                      <img src="../static/assets/img/icons/common/google.svg">
                    </span>
                    <span class="btn-inner--text">Google</span>
                  </a>
                </div>
              </div>
              <div class="card-body px-lg-5 py-lg-5">
                <div class="text-center text-muted mb-4">
                  <small>Or sign in with credentials</small>
                </div>
                <form role="form" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <div class="form-group mb-3">
                    <div class="input-group input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      <input class="form-control" placeholder="Email" type="email">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                      </div>
                      <input class="form-control" placeholder="Password" type="password">
                    </div>
                  </div>
                  <div class="custom-control custom-control-alternative custom-checkbox">
                    <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                    <label class="custom-control-label" for=" customCheckLogin">
                      <span>Remember me</span>
                    </label>
                  </div>
                  <div class="text-center">
                    <button type="submit" class="btn btn-primary my-4">Sign in</button>
                  </div>

                </form>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-6">
                <a href="#" class="text-light">
                  <small>Forgot password?</small>
                </a>
              </div>
              <div class="col-6 text-right">
                <a href="#" class="text-light">
                  <small>Create new account</small>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>

  <!-- Core -->
  <script src="../static/assets/vendor/jquery/jquery.min.js"></script>
  <script src="../static/assets/vendor/popper/popper.min.js"></script>
  <script src="../static/assets/vendor/bootstrap/bootstrap.min.js"></script>
  <script src="../static/assets/vendor/headroom/headroom.min.js"></script>
  <!-- Argon JS -->
  <script src="../static/assets/js/argon.js?v=1.0.1"></script>
</body>

</html>

gitpub/cms/templates/register.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="GitPub Team">
  <title>GitPub</title>
  <!-- Favicon -->
  <link href="../static/assets/img/brand/gitpub.png" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="../static/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
  <link href="../static/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="../static/assets/css/argon.css?v=1.0.1" rel="stylesheet">
  <!-- Docs CSS -->
  <link type="text/css" href="../static/assets/css/docs.min.css" rel="stylesheet">
</head>

<body>
  <main>
    <section class="section section-shaped">
      <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div class="container pt-lg-md">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="card bg-secondary shadow border-0">
              <div class="card-header bg-white pb-5">
                <div class="text-muted text-center mb-3">
                  <small>Sign up with</small>
                </div>
                <div class="text-center">
                  <a href="#" class="btn btn-neutral btn-icon mr-4">
                    <span class="btn-inner--icon">
                      <img src="../static/assets/img/icons/common/github.svg">
                    </span>
                    <span class="btn-inner--text">Github</span>
                  </a>
                  <a href="#" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon">
                      <img src="../static/assets/img/icons/common/google.svg">
                    </span>
                    <span class="btn-inner--text">Google</span>
                  </a>
                </div>
              </div>
              <div class="card-body px-lg-5 py-lg-5">
                <div class="text-center text-muted mb-4">
                  <small>Or sign up with credentials</small>
                </div>
                <form role="form">
                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      <input class="form-control" placeholder="Name" type="text">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      <input class="form-control" placeholder="Email" type="email">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                      </div>
                      <input class="form-control" placeholder="Password" type="password">
                    </div>
                  </div>
                  <div class="text-muted font-italic">
                    <small>password strength:
                      <span class="text-success font-weight-700">strong</span>
                    </small>
                  </div>
                  <div class="row my-4">
                    <div class="col-12">
                      <div class="custom-control custom-control-alternative custom-checkbox">
                        <input class="custom-control-input" id="customCheckRegister" type="checkbox">
                        <label class="custom-control-label" for="customCheckRegister">
                          <span>I agree with the
                            <a href="#">Privacy Policy</a>
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="text-center">
                    <button type="button" class="btn btn-primary mt-4">Create account</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  <!-- Core -->
  <script src="../static//vendor/jquery/jquery.min.js"></script>
  <script src="../static/assets/vendor/popper/popper.min.js"></script>
  <script src="../static/assets/vendor/bootstrap/bootstrap.min.js"></script>
  <script src="../static/assets/vendor/headroom/headroom.min.js"></script>
  <!-- Argon JS -->
  <script src="../static/assets/js/argon.js?v=1.0.1"></script>
</body>

</html>

gitpub/courses/templates/create_course_form.html
<form action="{% url 'courses:create_course_form_post' %}" method="post">
    {% csrf_token %}
    <div>
        <div>
            <input required placeholder="Nome Completo" type="text" name="user_first_name">
        </div>
        <div>
            <div>
                <input required placeholder="Email" type="text" name="user_email">
            </div>
        </div>
        <input type="hidden" name="extra_information" value="This is hidden information">
        <div>
            <input type="submit" value="Enviar">
        </div>
    </div>
</form>